-- Cube Academy — schema Supabase (Postgres)
-- Esegui una volta nel SQL Editor di Supabase, poi importa i dati con corsi_seed_supabase.sql.

-- ---------------------------------------------------------------------------
-- Tabella corsi (equivalente di wp_corsi, con nomi colonna snake_case)
-- ---------------------------------------------------------------------------
create table if not exists public.corsi (
  id_corso                    bigint generated by default as identity primary key,
  titolo                      text        not null,
  livello                     text        not null default 'Foundation',
  -- 0=In Programma 1=Confermato 2=Non visualizzato 3=Non Confermato 4=In corso 5=Completato
  stato                       smallint    not null default 0 check (stato between 0 and 5),
  in_evidenza                 boolean     not null default false,
  iscrizioni_aperte           boolean     not null default false,
  standard_price              integer     check (standard_price >= 0),
  early_bird_price            integer     check (early_bird_price >= 0),
  early_bird_start            timestamptz,
  early_bird_end              timestamptz,
  early_bird_percentuale      numeric(5,2) not null default 0,
  data_inizio                 date,
  data_fine                   date,
  posti_totali                integer     check (posti_totali >= 0),
  posti_disponibili           integer     check (posti_disponibili >= 0),

  data_it text, data_en text, data_fr text, data_de text,
  luogo_it text, luogo_en text, luogo_fr text, luogo_de text,
  lingua_it text, lingua_en text, lingua_fr text, lingua_de text,
  note_it text, note_en text, note_fr text, note_de text,
  link_readmore_it text not null default '', link_readmore_en text not null default '',
  link_readmore_fr text not null default '', link_readmore_de text not null default '',
  link_booking_it  text not null default '', link_booking_en  text not null default '',
  link_booking_fr  text not null default '', link_booking_de  text not null default '',
  home_subtitle_it text not null default '', home_subtitle_en text not null default '',
  home_subtitle_fr text not null default '', home_subtitle_de text not null default '',
  read_more_it text, read_more_en text, read_more_fr text, read_more_de text,

  codice_sconto_1 text, codice_sconto_1_data_inizio timestamptz, codice_sconto_1_data_fine timestamptz, codice_sconto_1_percentuale numeric(5,2),
  codice_sconto_2 text, codice_sconto_2_data_inizio timestamptz, codice_sconto_2_data_fine timestamptz, codice_sconto_2_percentuale numeric(5,2),
  codice_sconto_3 text, codice_sconto_3_data_inizio timestamptz, codice_sconto_3_data_fine timestamptz, codice_sconto_3_percentuale numeric(5,2),
  codice_sconto_privati text
);

-- ---------------------------------------------------------------------------
-- Amministratori: solo le email elencate qui possono modificare i corsi.
-- (Gli utenti si creano da Authentication > Users; qui li si abilita.)
-- ---------------------------------------------------------------------------
create table if not exists public.admin_emails (email text primary key);
alter table public.admin_emails enable row level security; -- nessuna policy: non leggibile dal client

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.admin_emails
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

-- ---------------------------------------------------------------------------
-- Sicurezza: la tabella base è accessibile solo agli admin
-- ---------------------------------------------------------------------------
alter table public.corsi enable row level security;

drop policy if exists corsi_admin_all on public.corsi;
create policy corsi_admin_all on public.corsi
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Vista pubblica: solo i corsi visibili e solo i campi sicuri
-- (niente codici sconto, niente HTML lungo). È ciò che legge il sito.
-- Le viste girano con i permessi del proprietario, quindi bypassano la RLS della tabella.
-- ---------------------------------------------------------------------------
create or replace view public.corsi_public as
select
  id_corso, titolo, livello, stato, in_evidenza, iscrizioni_aperte,
  standard_price, early_bird_price, early_bird_start, early_bird_end, early_bird_percentuale,
  data_inizio, data_fine, posti_totali, posti_disponibili,
  data_it, data_en, data_fr, data_de,
  luogo_it, luogo_en, luogo_fr, luogo_de,
  lingua_it, lingua_en, lingua_fr, lingua_de,
  link_booking_it, link_booking_en, link_booking_fr, link_booking_de
from public.corsi
where stato in (0, 1, 3, 4, 5); -- 2 = "Non visualizzato" resta nascosto

revoke all on public.corsi_public from public;
grant select on public.corsi_public to anon, authenticated;
